name: Production Release to Cloud Run
on:
  release:
    types: [published]
jobs:
  release:
  
    if: ${{ github.ref == 'refs/heads/main' }}
    
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: prod
    secrets: inherit
