name: Build and Deploy to Cloud Run

on:
  push:
    branches: [develop, main]
    paths:
      - 'service-yaml/container-dev.yaml'
      - 'service-yaml/container-qa.yaml'

jobs:
  check_changes_dev:  # New job to check for file changes 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify Changed files Dev
      uses: tj-actions/changed-files@v45
      id: verify-changed-files-dev
      with:
          files: |
             service-yaml/container-dev.yaml

  check_changes_qa:  # New job to check for file changes 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify Changed files QA
      uses: tj-actions/changed-files@v45
      id: verify-changed-files-qa
      with:
          files: |
             service-yaml/container-qa.yaml


  dev:
    if: (github.ref_name == 'develop' || github.base_ref == 'develop') && needs.verify-changed-files-dev.outputs.any_modified == 'true' 
    needs: check_changes_dev
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: dev
    secrets: inherit

  qa:
    needs: check_changes_qa
    if: (github.ref_name == 'main' || github.base_ref == 'main') && needs.verify-changed-files-qa.outputs.any_modified == 'true'
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: qa
    secrets: inherit
