name: Build and Deploy to Cloud Run

on:
  push:
    branches: [develop, main]
    paths:
      - 'service-yaml/container-dev.yaml'
      - 'service-yaml/container-qa.yaml'

jobs:
  
  check_changes:  # New job to check for file changes 
    outputs:
      dev: ${{steps.verify-changed-files.outputs.dev_any_changed}}
      qa: ${{steps.verify-changed-files.outputs.qa_any_changed}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Verify Changed files Dev
      
      uses: tj-actions/changed-files@v45
      id: verify-changed-files
      with:
        files_yaml: |
          dev: &dev
            - service-yaml/container-dev.yaml
          qa: &qa
            - service-yaml/container-qa.yaml
            

  dev:
    needs: [check_changes]
    if: ${{ github.ref == 'refs/heads/develop' && needs.check_changes.outputs.dev == 'true'}}
    
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: dev
    secrets: inherit

  qa:
    needs: [check_changes]
    if: ${{ github.ref == 'refs/heads/main' && needs.check_changes.outputs.qa == 'true' }}
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: qa
    secrets: inherit
