name: Build and Deploy to Cloud Run

on:
  push:
    branches: [develop, main]
    paths:
      - 'service-yaml/container-dev.yaml'
      - 'service-yaml/container-qa.yaml'

jobs:
  
  check_changes:  # New job to check for file changes 
    outputs:
      dev: ${{steps.verify-changed-files.outputs.dev_any_changed}}
      qa: ${{steps.verify-changed-files.outputs.qa_any_changed}}
      changed_dev: ${{steps.dev-changed.changed}}
      changed_qa: ${{steps.qa-changed.changed}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Verify Changed files Dev
      
      uses: tj-actions/changed-files@v45
      id: verify-changed-files
      with:
        files_yaml: |
          dev: &dev
            - service-yaml/container-dev.yaml
          qa: &qa
            - service-yaml/container-qa.yaml
            
    - name: output which file change for dev
      id: dev-changed
      env:
        CHANGED: ${{ steps.verify-changed-files.outputs.dev_any_changed }}
      run: |
        echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
    - name: output which file change for dev
      id: qa-changed
      env:
        CHANGED: ${{ steps.verify-changed-files.outputs.qa_any_changed }}
      run: |
        echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
  test:
    needs: [check_changes]
    runs-on: ubuntu-latest
    steps:
      - env: 
          DEV: ${{needs.check_changes.outputs.dev}}
          QA: ${{needs.check_changes.outputs.qa}}
          CHANGED_DEV: ${{needs.check_changes.outputs.changed_dev}}
          CHANGED_QA: ${{needs.check_changes.outputs.changed_qa}}
        run: echo "$DEV $QA $CHANGED_DEV $CHANGED_QA"

  dev:
    needs: [test]
    if: (github.ref_name == 'develop' || github.base_ref == 'develop') && ${{ needs.check_changes.outputs.dev == 'true' }}
    
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: dev
    secrets: inherit

  qa:
    needs: [check_changes]
    if: (github.ref_name == 'main' || github.base_ref == 'main') && needs.check_changes.outputs.qa == 'true'
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: qa
    secrets: inherit
