name: Build and Deploy to Cloud Run

on:
  push:
    branches: [develop, main]
    paths:
      - 'service-yaml/container-dev.yaml'
      - 'service-yaml/container-qa.yaml'

jobs:
  check_changes:  # New job to check for file changes 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for changes in service-yaml
      id: check_changes  # Set an ID for this step to access its output
      run: |
        if [[ -n $(git diff --name-only HEAD^ HEAD | grep "service-yaml/container-${{ github.ref_name == 'develop' && 'dev' || 'qa' }}.yaml") ]]; then
          echo "::set-output name=changes_exist::true"
        fi
  dev:
    if: github.ref_name == 'develop' || github.base_ref == 'develop' && needs.check_changes.outputs.changes_exist == 'true' 
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: dev
    secrets: inherit

  qa:
    needs: check_changes
    if: github.ref_name == 'main' || github.base_ref == 'main' && needs.check_changes.outputs.changes_exist == 'true' 
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: qa
    secrets: inherit
