name: Build and Deploy to Cloud Run

on:
  push:
    branches: [develop, main]
    paths:
      - 'service-yaml/container-dev.yaml'
      - 'service-yaml/container-qa.yaml'

jobs:
  
  check_changes:  # New job to check for file changes 
    outputs:
      dev: ${{steps.verify-changed-files.outputs.dev_all_changed_files}}
      qa: ${{steps.verify-changed-files.outputs.qa_all_changed_files}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Verify Changed files Dev
      
      uses: tj-actions/changed-files@v45
      id: verify-changed-files
      with:
        files_yaml: |
          dev: &dev
            - service-yaml/container-dev.yaml
          qa: &qa
            - service-yaml/container-qa.yaml
            
    - name: Run step if test file(s) change
      # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
      if: steps.changed-files-yaml.outputs.test_any_changed == 'true'  
      env:
        TEST_ALL_CHANGED_FILES: ${{ steps.verify-changed-files.outputs.dev_all_changed_files }}
      run: |
        echo "One or more test file(s) has changed."
        echo "List all the files that have changed: $TEST_ALL_CHANGED_FILES"
    - id: changed-files
      uses: tj-actions/changed-files@v45
    # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
    
 


  dev:
    needs: [check_changes]
    if: (github.ref_name == 'develop' || github.base_ref == 'develop') && needs.check_changes.outputs.dev == 'true' 
    
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: dev
    secrets: inherit

  qa:
    needs: [check_changes]
    if: (github.ref_name == 'main' || github.base_ref == 'main') && needs.check_changes.outputs.qa == 'true'
    uses: ./.github/workflows/cloud-run-service-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: qa
    secrets: inherit
