name: Build and Deploy to Cloud Run
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  #DEV
  dev:
    if: github.ref_name == 'develop'
    uses: ./.github/workflows/cloud-run-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: dev
    secrets: inherit
  qa:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/cloud-run-deployment.yml
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
      checks: write
      pull-requests: write
    with:
      environment: qa
    secrets: inherit
